sudo: required
services:
  - docker

before_install:
  - docker build -t sivasundar24/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true sivasundar24/react-test npm test

after_install:
  - docker build -t sivasundar24/multi-client -f ./client
  - docker build -t sivasundar24/multi-server -f ./server
  - docker build -t sivasundar24/multi-nginx -f ./nginx
  - docker build -t sivasundar24/multi-worker -f ./worker    